### ISSUE TITLE
Polish flag patch

### ISSUE THREAD

**Issue by Rajdoslav** [SleepyAsh17/CCMT-A3-Insignias#4]
![Polish Flag Patch](https://ae01.alicdn.com/kf/HTB1XGZINXXXXXcPaXXXq6xXFXXXP/Embroidered-Poland-Flag-Patches-Army-Hook-Loop-Patch-3D-Tactical-Military-Patches-Fabric-Armband-National-Flag.jpg_640x640.jpg)

**Comment by xwirkijowski** [comment]
Added as `[FLAG] Poland`, created by @RaixHQ
